[project]
name = "sequence"
version = "0.8.0"
authors = [
    { name = "Xiaoliang Wu, Joaquin Chung, Alexander Kolar, Alexander Kiefer, Eugene Wang, Tian Zhong, Rajkumar Kettimuthu, Martin Suchara, Robert Hayek, Ansh Singal, Caitao Zhan", email = "czhan@anl.gov" }
]
maintainers = [
    { name = "Caitao Zhan", email = "czhan@anl.gov" }
]
description = "Simulator of QUantum Network Communication (SeQUeNCe) is an open-source tool that allows modeling of quantum networks including photonic network components, control protocols, and applications."
readme = "README.md"
requires-python = ">=3.10, <3.14"
classifiers = [
    "Programming Language :: Python :: 3.10",
    "Programming Language :: Python :: 3.11",
    "Programming Language :: Python :: 3.12",
    "Programming Language :: Python :: 3.13",
]
dynamic = ["dependencies"]
keywords = ["quantum", "network", "discrete", "event", "simulator"]

[tool.setuptools.dynamic]
dependencies = { file = ["requirements.txt"] }

[tool.setuptools]
packages = ['sequence', 'sequence.app', 'sequence.kernel', 'sequence.components', 'sequence.network_management',
            'sequence.entanglement_management', 'sequence.qkd', 'sequence.resource_management', 'sequence.topology',
            'sequence.utils', 'sequence.gui', 'sequence.qlan', 'sequence.topology.qlan',
            'sequence.entanglement_management.generation', 'sequence.entanglement_management.purification']

[tool.setuptools.package-data]
sequence = ["gui/user_templates.json", "gui/default_params.json", "gui/starlight.json"]

[project.urls]
Homepage = "https://github.com/sequence-toolbox/SeQUeNCe"
Documentation = "https://sequence-rtd-tutorial.readthedocs.io/"
Issues = "https://github.com/sequence-toolbox/SeQUeNCe/issues"
Changelog = "https://github.com/sequence-toolbox/SeQUeNCe/blob/master/CHANGELOG.md"
